# Generated by Django 6.1.1 on 2026-10-04 19:18

import common.ids
import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0004_call_exportjob_fieldchange_leaddiscussion_and_more'),
        ('users', '0002_user_must_change_password_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('channel', models.CharField(max_length=10)),
                ('audience', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('counts', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user')),
            ],
            options={
                'db_table': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('channel', models.CharField(choices=[('sms', 'sms'), ('email', 'email'), ('whatsapp', 'whatsapp')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('dlt_template_id', models.CharField(blank=True, max_length=40, null=True)),
                ('sender_id', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user')),
            ],
            options={
                'db_table': 'message_templates',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=10)),
                ('trigger', models.CharField(blank=True, max_length=40, null=True)),
                ('to_address', models.CharField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('status', models.CharField(db_index=True, default='queued', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=30, null=True)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('sent_by_label', models.CharField(blank=True, max_length=100, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.leadactivity')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='leads.lead')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messaging.messagetemplate')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='messaging.messagetemplate'),
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(max_length=40)),
                ('channel', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messaging.messagetemplate')),
            ],
            options={
                'db_table': 'automation_rules',
            },
        ),
        migrations.AddConstraint(
            model_name='messagetemplate',
            constraint=models.UniqueConstraint(fields=('channel', 'name'), name='template_channel_name_unique'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['lead', '-created_at'], name='messages_lead_id_b45945_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['lead', 'trigger', 'created_at'], name='messages_lead_id_b08c68_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationrule',
            constraint=models.UniqueConstraint(fields=('trigger', 'channel'), name='automation_trigger_channel_unique'),
        ),
    ]
