# Generated by Django 6.1.1 on 2026-10-04 17:28

import common.ids
import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_name', models.CharField(max_length=100)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('module', models.CharField(db_index=True, max_length=30)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=50, null=True)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
    ]
