# Generated by Django 6.1.1 on 2026-10-04 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['module', '-created_at'], name='audit_logs_module_31f3f7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', '-created_at'], name='audit_logs_actor_i_3b0e80_idx'),
        ),
    ]
