# Generated by Django 6.1.1 on 2026-10-04 17:28

import common.ids
import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('type', models.CharField(choices=[('lead_assigned', 'lead_assigned'), ('lead_reassigned', 'lead_reassigned'), ('task_due', 'task_due'), ('task_overdue', 'task_overdue'), ('payment', 'payment'), ('application', 'application'), ('interview', 'interview'), ('exam', 'exam'), ('system', 'system')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
