# Generated by Django 6.1.1 on 2026-10-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('lead_assigned', 'lead_assigned'), ('lead_reassigned', 'lead_reassigned'), ('task_due', 'task_due'), ('task_overdue', 'task_overdue'), ('payment', 'payment'), ('application', 'application'), ('interview', 'interview'), ('exam', 'exam'), ('system', 'system'), ('re_enquiry', 're_enquiry'), ('unassigned_pool', 'unassigned_pool'), ('language_barrier', 'language_barrier'), ('untouched', 'untouched'), ('bulk_done', 'bulk_done'), ('export_ready', 'export_ready'), ('integration_error', 'integration_error')], max_length=30),
        ),
    ]
