import type { Lead } from "./types";

/**
 * Placeholder data for the Lead Manager module. Replace with the Lead service
 * APIs (see leadSlice stubs) once the backend endpoints exist.
 */
export const LEAD_STAGES = [
  "Untouched",
  "Contacted",
  "Follow-up",
  "Interested",
  "Application",
  "Enrolled",
  "Closed",
];

export const LEAD_SOURCES = [
  "direct",
  "publisher A",
  "referral",
  "organic",
  "google",
  "facebook",
  "walk-in",
  "telephony",
];

export const MOCK_COUNSELORS = [
  { label: "Neha Kapoor", value: "neha-kapoor" },
  { label: "Arjun Mehta", value: "arjun-mehta" },
  { label: "Priya Raman", value: "priya-raman" },
  { label: "Rohan Das", value: "rohan-das" },
];

export const MOCK_LEADS: Lead[] = [
  {
    id: 1,
    name: "Rahul Kumar",
    email: "rahul.kumar@gmail.com",
    mobile: "9910000017",
    source: "direct",
    medium: "direct",
    campaign: "direct",
    course: "MBA",
    lead_stage: "Untouched",
    city: "Gurugram",
    state: "Haryana",
    assigned_to: "Neha Kapoor",
    last_activity: "Today",
    queries: [
      { id: 1, question: "What is the fee structure for MBA?", status: "Open", created_at: "2026-09-27T11:20:00" },
    ],
    activities: [
      { id: 1, action: "Lead Registered", description: "Registered via direct campaign.", created_at: "2026-09-25T04:15:47" },
    ],
    created_at: "2026-09-25T04:15:47",
    updated_at: "2026-09-28T10:05:00",
  },
  {
    id: 2,
    name: "Rohan Sharma",
    email: "rohan.sharma@gmail.com",
    mobile: "9910000028",
    source: "publisher A",
    medium: "banner",
    campaign: "launch",
    course: "BTech",
    lead_stage: "Contacted",
    city: "Delhi",
    state: "Delhi",
    assigned_to: "Arjun Mehta",
    last_activity: "Yesterday",
    queries: [],
    activities: [
      { id: 1, action: "Lead Registered", description: "Registered via publisher A banner.", created_at: "2026-09-22T09:30:00" },
      { id: 2, action: "Call Attempted", description: "First outreach call made.", created_at: "2026-09-23T12:10:00" },
    ],
    created_at: "2026-09-22T09:30:00",
    updated_at: "2026-09-27T15:40:00",
  },
  {
    id: 3,
    name: "Radhika Jain",
    email: "radhika.jain@gmail.com",
    mobile: "9910000039",
    source: "referral",
    medium: "TOI",
    campaign: "article",
    course: "BBA",
    lead_stage: "Follow-up",
    city: "Jaipur",
    state: "Rajasthan",
    assigned_to: "Priya Raman",
    last_activity: "2 days ago",
    queries: [
      { id: 1, question: "Is hostel accommodation available?", status: "Answered", created_at: "2026-09-20T14:00:00" },
      { id: 2, question: "Can I pay the fee in installments?", status: "Open", created_at: "2026-09-24T10:45:00" },
    ],
    activities: [
      { id: 1, action: "Lead Registered", description: "Registered via TOI article referral.", created_at: "2026-09-18T08:20:00" },
      { id: 2, action: "Follow-up Scheduled", description: "Callback set for next week.", created_at: "2026-09-24T11:00:00" },
    ],
    created_at: "2026-09-18T08:20:00",
    updated_at: "2026-09-26T09:15:00",
  },
  {
    id: 4,
    name: "Khushi Gupta",
    email: "khushi.gupta@gmail.com",
    mobile: "9910000044",
    source: "organic",
    medium: "google",
    campaign: "search",
    course: "MBA",
    lead_stage: "Interested",
    city: "Noida",
    state: "Uttar Pradesh",
    assigned_to: "Neha Kapoor",
    last_activity: "Today",
    queries: [],
    activities: [
      { id: 1, action: "Lead Registered", description: "Found us via organic google search.", created_at: "2026-09-15T16:45:00" },
      { id: 2, action: "Brochure Sent", description: "MBA brochure shared over email.", created_at: "2026-09-19T13:25:00" },
    ],
    created_at: "2026-09-15T16:45:00",
    updated_at: "2026-09-28T08:50:00",
  },
  {
    id: 5,
    name: "Shruti Singh",
    email: "shruti.singh@gmail.com",
    mobile: "9910000055",
    source: "google",
    medium: "searchAd",
    campaign: "BTech",
    course: "BTech",
    lead_stage: "Application",
    city: "Lucknow",
    state: "Uttar Pradesh",
    assigned_to: "Rohan Das",
    last_activity: "3 days ago",
    queries: [
      { id: 1, question: "What documents are needed for the application?", status: "Answered", created_at: "2026-09-21T09:00:00" },
    ],
    activities: [
      { id: 1, action: "Lead Registered", description: "Came in through google search ad.", created_at: "2026-09-12T10:05:00" },
      { id: 2, action: "Application Started", description: "BTech application form initiated.", created_at: "2026-09-22T17:30:00" },
    ],
    created_at: "2026-09-12T10:05:00",
    updated_at: "2026-09-25T12:00:00",
  },
  {
    id: 6,
    name: "Vansh Kapoor",
    email: "vansh.kapoor@gmail.com",
    mobile: "9910000066",
    source: "facebook",
    medium: "leadAd",
    campaign: "BBA",
    course: "BBA",
    lead_stage: "Follow-up",
    city: "Chandigarh",
    state: "Punjab",
    assigned_to: "Arjun Mehta",
    last_activity: "Today",
    queries: [],
    activities: [
      { id: 1, action: "Lead Registered", description: "Submitted facebook lead ad form.", created_at: "2026-09-10T19:40:00" },
    ],
    created_at: "2026-09-10T19:40:00",
    updated_at: "2026-09-28T11:10:00",
  },
  {
    id: 7,
    name: "Javed Ansari",
    email: "javed.ansari@gmail.com",
    mobile: "9910000077",
    source: "walk-in",
    medium: "QRcode",
    campaign: "frontdesk",
    course: "MCA",
    lead_stage: "Enrolled",
    city: "Mumbai",
    state: "Maharashtra",
    assigned_to: "Priya Raman",
    last_activity: "1 week ago",
    queries: [
      { id: 1, question: "When does the next batch start?", status: "Answered", created_at: "2026-09-08T12:30:00" },
    ],
    activities: [
      { id: 1, action: "Lead Registered", description: "Walk-in registration via front desk QR code.", created_at: "2026-09-05T11:15:00" },
      { id: 2, action: "Enrolled", description: "Admission confirmed for MCA.", created_at: "2026-09-20T15:00:00" },
    ],
    created_at: "2026-09-05T11:15:00",
    updated_at: "2026-09-20T15:00:00",
  },
  {
    id: 8,
    name: "Aakriti Gupta",
    email: "aakriti.gupta@gmail.com",
    mobile: "9910000088",
    source: "organic",
    medium: "bing",
    campaign: "search",
    course: "BCA",
    lead_stage: "Contacted",
    city: "Indore",
    state: "Madhya Pradesh",
    assigned_to: "Rohan Das",
    last_activity: "Yesterday",
    queries: [],
    activities: [
      { id: 1, action: "Lead Registered", description: "Found us via organic bing search.", created_at: "2026-09-02T14:50:00" },
      { id: 2, action: "Call Connected", description: "Spoke about BCA curriculum.", created_at: "2026-09-27T10:20:00" },
    ],
    created_at: "2026-09-02T14:50:00",
    updated_at: "2026-09-27T10:20:00",
  },
  {
    id: 9,
    name: "Jyoti Mishra",
    email: "jyoti.mishra@gmail.com",
    mobile: "9910000099",
    source: "telephony",
    medium: "inbound",
    campaign: "NA",
    course: "MBA",
    lead_stage: "Closed",
    city: "Patna",
    state: "Bihar",
    assigned_to: "Neha Kapoor",
    last_activity: "2 weeks ago",
    queries: [
      { id: 1, question: "Do you offer weekend classes?", status: "Answered", created_at: "2026-08-28T13:10:00" },
    ],
    activities: [
      { id: 1, action: "Lead Registered", description: "Inbound telephony enquiry.", created_at: "2026-08-25T09:05:00" },
      { id: 2, action: "Closed", description: "Not interested this intake.", created_at: "2026-09-14T16:35:00" },
    ],
    created_at: "2026-08-25T09:05:00",
    updated_at: "2026-09-14T16:35:00",
  },
  {
    id: 10,
    name: "Priyanshu Verma",
    email: "priyanshu.verma@gmail.com",
    mobile: "9910000110",
    source: "google",
    medium: "searchAd",
    campaign: "MBA",
    course: "MBA",
    lead_stage: "Untouched",
    city: "Kanpur",
    state: "Uttar Pradesh",
    assigned_to: "Arjun Mehta",
    last_activity: "Today",
    queries: [],
    activities: [
      { id: 1, action: "Lead Registered", description: "Came in through google search ad.", created_at: "2026-09-28T07:55:00" },
    ],
    created_at: "2026-09-28T07:55:00",
    updated_at: "2026-09-28T07:55:00",
  },
];

export default MOCK_LEADS;
