# Generated by Django 6.1.1 on 2026-10-04 19:18

import common.ids
import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0003_lead_untouched_alerted_at'),
        ('users', '0002_user_must_change_password_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFormMapping',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_id', models.CharField(max_length=64, unique=True)),
                ('form_name', models.CharField(blank=True, max_length=255, null=True)),
                ('page_id', models.CharField(blank=True, max_length=64, null=True)),
                ('mapping', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user')),
            ],
            options={
                'db_table': 'meta_form_mappings',
            },
        ),
        migrations.CreateModel(
            name='MetaLeadEvent',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leadgen_id', models.CharField(max_length=64, unique=True)),
                ('page_id', models.CharField(blank=True, max_length=64, null=True)),
                ('form_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('ad_id', models.CharField(blank=True, max_length=64, null=True)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='received', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.lead')),
            ],
            options={
                'db_table': 'meta_lead_events',
            },
        ),
    ]
