# Generated by Django 6.1.1 on 2026-10-04 18:38

import common.ids
import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0003_lead_untouched_alerted_at'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('call_back', 'Call Back'), ('follow_up_call', 'Follow-up Call'), ('counselling_session', 'Counselling Session'), ('expert_one_on_one', 'Expert One-on-One'), ('document_collection', 'Document Collection'), ('payment_follow_up', 'Payment Follow-up'), ('parent_call', 'Parent Call'), ('other', 'Other')], max_length=30)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('priority', models.CharField(default='normal', max_length=10)),
                ('reminder_minutes', models.IntegerField(default=15)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(db_index=True, default='open', max_length=10)),
                ('outcome', models.CharField(blank=True, max_length=500, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('overdue_notified_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='users.user')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='leads.lead')),
            ],
            options={
                'db_table': 'tasks',
                'indexes': [models.Index(fields=['assignee', 'status', 'due_at'], name='tasks_assigne_3497fa_idx'), models.Index(fields=['lead', 'status'], name='tasks_lead_id_c7d326_idx')],
            },
        ),
    ]
