# Generated by Django 6.1.1 on 2026-10-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('call_back', 'Call back'), ('follow_up_call', 'Follow-up call'), ('counselling_session', 'Counselling session'), ('expert_one_on_one', 'Expert one-on-one'), ('document_collection', 'Document collection'), ('other', 'Other')], max_length=30),
        ),
    ]
