# Generated by Django 6.1.1 on 2026-10-04 17:28

import apps.leads.models
import common.ids
import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('seq', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'counters',
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('actor_type', models.CharField(default='system', max_length=10)),
                ('actor_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'lead_activities',
            },
        ),
        migrations.CreateModel(
            name='LeadProfile',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal', models.JSONField(blank=True, null=True)),
                ('guardian', models.JSONField(blank=True, null=True)),
                ('academic', models.JSONField(blank=True, null=True)),
                ('work', models.JSONField(blank=True, null=True)),
                ('declaration', models.JSONField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('unlock_history', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'lead_profiles',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'notes',
            },
        ),
        migrations.CreateModel(
            name='RoundRobinState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'round_robin_state',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_no', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('alt_mobile', models.CharField(blank=True, max_length=16, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='India', max_length=100, null=True)),
                ('utm', models.JSONField(default=dict)),
                ('referral', models.JSONField(default=dict)),
                ('track', models.CharField(default='other', max_length=10)),
                ('stage_changed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=10)),
                ('last_disposition', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('consent', models.JSONField(default=apps.leads.models.default_consent)),
                ('custom_fields', models.JSONField(default=dict)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(default='manual', max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.cohort')),
            ],
            options={
                'db_table': 'leads',
            },
        ),
    ]
