# Generated by Django 6.1.1 on 2026-10-04 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('masters', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user'),
        ),
        migrations.AddField(
            model_name='lead',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user'),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.source'),
        ),
        migrations.AddField(
            model_name='lead',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to='users.user'),
        ),
        migrations.AddField(
            model_name='lead',
            name='program_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.program'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.source'),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='masters.stage'),
        ),
        migrations.AddField(
            model_name='lead',
            name='sub_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.substage'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='leads', to='masters.tag'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadprofile',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user'),
        ),
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.user'),
        ),
        migrations.AddField(
            model_name='note',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='roundrobinstate',
            name='last_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['owner', 'stage'], name='leads_owner_i_3346cc_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['stage'], name='leads_stage_i_8bd381_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='leads_source__1d615d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['first_name', 'last_name'], name='leads_first_n_6baaef_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('mobile',), name='lead_mobile_unique_live'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), ('is_deleted', False)), fields=('email',), name='lead_email_unique_live'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead', '-created_at'], name='lead_activi_lead_id_d58c46_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['lead', '-created_at'], name='notes_lead_id_33a3e0_idx'),
        ),
    ]
