# Generated by Django 6.1.1 on 2026-10-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='untouched_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
