# Generated by Django 6.1.1 on 2026-10-04 19:18

import common.ids
import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_untouched_alerted_at'),
        ('masters', '0001_initial'),
        ('users', '0002_user_must_change_password_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(default='outbound', max_length=10)),
                ('status', models.CharField(default='answered', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('recording_url', models.CharField(blank=True, max_length=500, null=True)),
                ('dialer_call_id', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calls',
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('params', models.JSONField(default=dict)),
                ('format', models.CharField(default='xlsx', max_length=5)),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/%Y/%m/')),
                ('row_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'export_jobs',
            },
        ),
        migrations.CreateModel(
            name='FieldChange',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('section', models.CharField(max_length=20)),
                ('field', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=150)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_by_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'lead_field_changes',
            },
        ),
        migrations.CreateModel(
            name='LeadDiscussion',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'lead_discussions',
            },
        ),
        migrations.CreateModel(
            name='LeadDocument',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='lead-documents/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('is_current', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lead_documents',
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('params', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'saved_filters',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='last_enquired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='lead',
            name='meta_form_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='meta_lead_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='not_connected_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='not_connected_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='re_enquiry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='untouched_early_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='upload_file_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roundrobinstate',
            name='last_position',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['last_activity_at'], name='leads_last_ac_87ffc8_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['city'], name='leads_city_5fb92b_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('meta_lead_id__isnull', False)), fields=('meta_lead_id',), name='lead_meta_id_unique'),
        ),
        migrations.AddField(
            model_name='call',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='call',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.stage'),
        ),
        migrations.AddField(
            model_name='call',
            name='sub_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.substage'),
        ),
        migrations.AddField(
            model_name='call',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='users.user'),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='users.user'),
        ),
        migrations.AddField(
            model_name='fieldchange',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user'),
        ),
        migrations.AddField(
            model_name='fieldchange',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_changes', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leaddiscussion',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leaddiscussion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user'),
        ),
        migrations.AddField(
            model_name='leaddocument',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leaddocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user'),
        ),
        migrations.AddField(
            model_name='savedfilter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['lead', '-created_at'], name='calls_lead_id_38f662_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldchange',
            index=models.Index(fields=['lead', '-created_at'], name='lead_field__lead_id_5a4754_idx'),
        ),
        migrations.AddIndex(
            model_name='leaddocument',
            index=models.Index(fields=['lead', 'doc_type', 'is_current'], name='lead_docume_lead_id_dff621_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedfilter',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='saved_filter_name_unique'),
        ),
    ]
