# Generated by Django 6.1.1 on 2026-10-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_gcc_lead_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaddiscussion',
            name='completion_percent',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='leadprofile',
            name='completion_percent',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
