# Generated by Django 6.1.1 on 2026-10-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='logged_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
