# Generated by Django 6.1.1 on 2026-10-04 17:28

import common.ids
import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionTemplate',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('permissions', models.JSONField(default=list)),
                ('data_scope', models.CharField(default='own', max_length=20)),
                ('field_rules', models.JSONField(default=list)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'permission_templates',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', common.models.ObjectIdField(default=common.ids.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('mobile', models.CharField(blank=True, max_length=16, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('receives_leads', models.BooleanField(default=False)),
                ('permissions', models.JSONField(default=list)),
                ('data_scope', models.CharField(choices=[('own', 'own'), ('team', 'team'), ('location', 'location'), ('program', 'program'), ('cohort', 'cohort'), ('all', 'all')], default='own', max_length=20)),
                ('field_rules', models.JSONField(default=list)),
                ('template_key', models.CharField(blank=True, max_length=50, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('password_reset_token_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('password_reset_expires', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='users.user')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='teams.team')),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['is_active', 'receives_leads'], name='users_is_acti_d40d30_idx')],
            },
        ),
    ]
